# Generated by Django 4.2.1 on 2023-10-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('Distributor', 'Distributor'), ('Wholesaler', 'Wholesaler'), ('Private label', 'Private label'), ('Other', 'Other')], max_length=255)),
                ('business_name', models.CharField(choices=[('Distributor', 'Distributor'), ('Wholesaler', 'Wholesaler'), ('Private label', 'Private label'), ('Other', 'Other')], max_length=255)),
                ('established_year', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
            ],
        ),
    ]
