# Generated by Django 4.2.6 on 2023-10-28 11:45

from django.db import migrations, models
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_zip_contact_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', tinymce_4.fields.TinyMCEModelField()),
            ],
        ),
    ]
